name: Windows CI
on: [] #[ push, pull_request ]
env:
  PROJECT_NAME: dol
jobs:
  windows-validation:
    name: Windows Validation
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Package
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          # If pytest is not already installed through setup.cfg or setup.py requirements,
          # include the line below:
          python -m pip install pytest

      - name: Run Tests
        run: python -m pytest
        # run: python -m pytest --maxfail=1 --disable-warnings

      # - name: Pytest Validation
      #   uses: i2mint/isee/actions/pytest-validation@master
      #   with:
      #     root-dir: ${{ env.PROJECT_NAME }}
      #     paths-to-ignore: scrap
